#!/bin/bash

for x in "${@}"; do
    plexignore="$(dirname "${x}")/.plexignore"
    name="$(basename "${x}")"
    [ -f "${x}" ] && echo "${name}" >> "${plexignore}"
    [ -d "${x}" ] && echo "${name}/*" >> "${plexignore}"
    sort -u -o "${plexignore}" "${plexignore}"
done
