#!/bin/bash
# 2020.12.29
# nemo script

# tells plex to ignore the selected files and/or directories

for x in "${@}"; do
    if [ -f "${x}" ]; then
        echo "${x}" >> .plexignore
    elif [ -d "${x}" ]; then
        echo "${x}/*" >> .plexignore
    fi
done

sort -u -o .plexignore .plexignore

