#!/bin/bash

# tidy
sort -k1n -k2n -o plex.tsv plex.tsv

# clear symlinks
mkdir -p __plex
find __plex -type l -exec rm {} \+

# process rows
while IFS=$'\t' read -r -a row; do

    # coalesce the target in case the season or episode is blank
    target="${row[2]:-${row[1]:-${row[0]}}}"

    # the target has to be ignored in the dir where it lives, not from a parent dir.
    [ -f "${target}" ] && echo "$(basename "${target}")" >> "$(dirname "${target}")/.plexignore"

    # skip symlinking if any fields are blank
    [ -z "${row[2]}" ] && continue

    # season number must be integer
    season=$(printf "S%02d" "${row[0]}") || continue;

    # expect the episode number to be an integer, but fall back to literal
    episode=$(printf "E%02d" "${row[1]}") || episode="E${row[1]}"

    # symlink with file extension
    ln -fsr "${target}" "__plex/${season}${episode}.${target##*.}"

done < plex.tsv

# tidy
find -name .plexignore -exec sort -u -o {} {} \;

