#!/bin/bash

for x in "${@}"; do
    plexignore="$(dirname "${x}")/.plexignore"
    [ -f "${plexignore}" ] || continue;
    name="$(basename "${x}")"
    [ -f "${x}" ] && grep -xv "${name}" "${plexignore}" > "${plexignore}~"
    [ -d "${x}" ] && grep -xv "${name}/\*" "${plexignore}" > "${plexignore}~"
    mv "${plexignore}~" "${plexignore}"
    [ ! -s "${plexignore}" ] && rm "${plexignore}"
done

