#!/bin/bash

# this script should be run from WITHIN a show root,
# but if we're somewhere else and running ON a show root then cd to it or exit.
if [ -n "${1}" ]; then
    cd "${1}" || exit
fi

source "$(dirname "${0}")/init.sh"

confirm(){ zenity --question --text="${1}" --width="$(( ${#1} * 10 ))"; }

if $(confirm "Clear symlinks?"); then
    find __plex -type l -exec rm {} \+
    for lma in behindthescenes deleted featurette interview scene short trailer other; do
        find -maxdepth 1 -type l -name "*-${lma}.*" -exec rm {} \+
    done
fi

if $(confirm "Clear .plexignore tree?"); then
    find -name .plexignore -exec rm {} \+
fi

if $(confirm "Clear emblems?"); then
    find -type d | while read d; do _setEmblems "${d}" ""; done
fi

