#!/bin/bash

ask() { zenity --entry --title="Condensed Episodes" --text="${1}" --entry-text="${2}"; }
i=$(ask "First episode number?" 1) || exit
total=$(ask "Last episode number?" 21) || exit
skip=$(ask "How many episodes per file?" 3) || exit

for (( i=$i; $i < $total; i += $skip )); do
    printf "%02d-E%02d\n" $i $(( $i + $skip - 1 ))
done | zenity --text-info

