#!/bin/bash

ask() { zenity --entry --title="Openings/Endings" --text="${1}" --entry-text="${2}"; }
opening=$(ask "Relative path to opening credits?")
ending=$(ask "Relative path to ending credits?")
s=$(ask "Season number?" 1) || exit
i=$(ask "First episode number?" 1) || exit

for x in "${@}"; do
    if [ ! -z "${opening}" ]; then
        printf "%d\t%02da\t%s\n" $s $i "${opening}"
        printf "%d\t%02db\t%s\n" $s $i "${x}"
        if [ ! -z "${ending}" ]; then
            printf "%d\t%02dc\t%s\n" $s $i "${ending}"
        fi
    elif [ ! -z "${ending}" ]; then
        printf "%d\t%02da\t%s\n" $s $i "${x}"
        printf "%d\t%02db\t%s\n" $s $i "${ending}"
    fi
    i=$(($i + 1))
done | zenity --text-info

