#!/bin/bash

ask() { zenity --entry --title="Openings/Endings" --text="${1}" --entry-text="${2}"; }
opening=$(ask "Relative path to opening credits?")
ending=$(ask "Relative path to ending credits?")
s=$(ask "Season number?" 1) || exit
e=$(ask "First episode number?" 1) || exit

for x in "${@}"; do
    if [ ! -z "${opening}" ]; then
        printf "%d\t%02d.pt1\t%s\n" $s $e "${opening}"
        printf "%d\t%02d.pt2\t%s\n" $s $e "${x}"
        if [ ! -z "${ending}" ]; then
            printf "%d\t%02d.pt3\t%s\n" $s $e "${ending}"
        fi
    elif [ ! -z "${ending}" ]; then
        printf "%d\t%02d.pt1\t%s\n" $s $e "${x}"
        printf "%d\t%02d.pt2\t%s\n" $s $e "${ending}"
    fi
    e=$(($e + 1))
done | zenity --text-info

