#!/bin/bash

ask() { zenity --entry --title="Split Episodes" --text="${1}" --entry-text="${2}"; }
first=$(ask "First episode number?" 1) || exit
last=$(ask "Last episode number?" 21) || exit
splits=$(ask "How many files per episode?" 3) || exit

letters=({a..z})
for (( i=$first; $i <= $last; i++ )); do
    for (( j=0; $j < $splits; j++ )); do
        printf "%02d%s\n" $i ${letters[$j]}
    done
done | zenity --text-info

