#!/bin/bash

for src in "${@}"; do

    # scan for regular files
    find "${src}" -type f -not -name '.*' | sort | while read target; do

        # only use videos
        [[ $(mimetype -b "${target}") == video/* ]] || continue

        # empty col 1 + col 2
        echo -en "\t\t" >> plex.tsv

        # col 3 without escape chars enabled
        echo "${target}" >> plex.tsv

    done
done

