#!/bin/bash
source "$(dirname "${0}")/init.sh"

touch plex.tsv
addEmblem plex.tsv $Sync

# scan for regular files
find "${@}" -type f | sort | while read target; do

    # only use videos
    [[ $(mimetype -b "${target}") == video/* ]] || continue

    # empty col 1 + col 2
    echo -en "\t\t" >> plex.tsv

    # col 3 without escape chars enabled
    echo "${target}" >> plex.tsv

done

rmEmblem plex.tsv $Sync

