#!/bin/bash
# this should ideally be run on the actual machine, and not a mount

hash="$(dirname "$(realpath "${0}")")/hash"
for x in "${@}"; do
    if [ -d "${x}" ]; then
        echo "${x}"
        cd "${x}"
        $hash
        cd - > /dev/null
    fi
done

