#!/bin/bash
[ -f plex.tsv ] || exit
source "$(dirname "$(realpath "${0}")")/../init.sh"

# process rows into ignores and symlinks
addEmblem plex.tsv $Sync
pinToTop plex.tsv
mkdir -p __
addEmblem __ $Sync
pinToTop __

while IFS=$'\t' read -r -a row; do

    # coalesce the target in case the season or episode is blank
    target="${row[2]:-${row[1]:-${row[0]}}}"

    # blank lines and comments
    [[ -z "${target}" || "${row::1}" = "#" ]] && continue

    # the target has to be ignored in the dir where it lives, not from a parent dir.
    echo "$(toPlexIgnore "${target}")" >> "$(dirname "${target}")/.plexignore"
    echo "$(toJellyIgnore "${target}")" >> "$(dirname "${target}")/.ignore"

    # skip symlinking if any fields are blank
    [ -z "${row[2]}" ] && continue
    targetName=$(basename "${target%.*}")
    targetExt="${target##*.}"

    # is the first col a tv season?
    if season=$(printf "S%02d" "${row[0]}" 2>/dev/null); then

        # expect the episode number to be an integer, but fall back to literal
        episode=$(printf "E%02d" "${row[1]}" 2>/dev/null) || episode="E${row[1]}"

        # symlink using file extension
        mkdir -p "__/${season}"
        ln -srf "${target}" "__/${season}/${season}${episode}.${targetExt}"

    # the first col is a local media asset type
    elif [[ "${row[0]}" =~ ^(behindthescenes|deleted|featurette|interview|scene|short|trailer|other)+$ ]]; then

        # expect "as-is" (hyphen), an index, or literal name.
        # sadly, the subdir-based extras do not follow any kind of predictable sorting when displayed,
        # so we have to symlink in the content root (the bloated "inline" way), which actually will sort alphabetically.
        # this is a known bug in plex that they have done nothing to resolve since the feature was added.
        if [ "${row[1]}" == "-" ]; then
            ln -srf "${target}" "${targetName}-${row[0]}.${targetExt}" # as-is
        elif idx=$(printf "%02d" "${row[1]}" 2>/dev/null); then
            ln -srf "${target}" "${idx}. ${targetName}-${row[0]}.${targetExt}" # indexed basename
        else
            ln -srf "${target}" "${row[1]}-${row[0]}.${targetExt}" # literal name
        fi

    fi

done < plex.tsv

# prune orphaned symlinks.
# we have to do it this way instead of simply clearing them all at the start
# because when plex sees a deletion it will remove them from playlists,
# even if they're immediately re-linked. we only want plex to see real changes.
# FIXME this has a race if plex.tsv has the same mtime as invocation. human lag should be enough.
find __ -type l -not -newer plex.tsv -exec rm {} \+
find __ -type l | while read each; do touch -h -r "$(realpath "${each}")" "${each}"; done # set mtime of symlinks to same as source files
find __ -type d -empty -exec rm -r {} \+
for lma in behindthescenes deleted featurette interview scene short trailer other; do
    find -maxdepth 1 -type l -name "*-${lma}.*" -not -newer plex.tsv -exec rm {} \+
done

# sort plex.tsv
# this must be done after pruning, because the old mtime is needed for that.
sort -n -k1,1 -k2,2 -t$'\t' -o plex.tsv plex.tsv

# sort plex and jellyfin ignore trees
find -name .plexignore -exec sort -u -o {} {} \;
find -name .ignore -exec sort -u -o {} {} \;

# done
rmEmblem __ $Sync
rmEmblem plex.tsv $Sync

# kill the old dir that confuses plex
rm -rf __plex

